/**
 * Mock data for SAARTH V0
 * All mock data is centralized here and not hardcoded in components.
 */

import { generateId } from './utils';

export const MOCK_USER = {
  id: 'user-1',
  name: 'Arjun Sharma',
  email: 'arjun@example.com',
  avatar: null,
  createdAt: '2026-01-15',
};

export const MOCK_VEHICLES = [
  {
    id: 'vehicle-1',
    name: 'My Swift',
    vehicleNumber: 'UP16XX1234',
    type: 'Car',
    fuelType: 'Petrol',
    model: 'Maruti Suzuki Swift VXi',
    year: 2022,
    currentOdometer: 42350,
    createdAt: '2026-01-15',
  },
  {
    id: 'vehicle-2',
    name: 'Commuter Bike',
    vehicleNumber: 'UP16YY5678',
    type: 'Bike',
    fuelType: 'Petrol',
    model: 'Honda Activa 6G',
    year: 2023,
    currentOdometer: 18200,
    createdAt: '2026-03-10',
  },
];

export const MOCK_FUEL_EVENTS = [
  {
    id: 'fuel-1',
    vehicleId: 'vehicle-1',
    date: '2026-10-04',
    amountPaid: 2500,
    pricePerLitre: 96.72,
    estimatedLitres: 25.85,
    odometer: 42350,
    distanceSinceLast: 352,
    mileage: 13.61,
    costPerKm: 7.1,
    fuelStation: 'HP Petrol Pump, Sector 18',
    paymentMethod: 'UPI',
    fuelType: 'Petrol',
  },
  {
    id: 'fuel-2',
    vehicleId: 'vehicle-1',
    date: '2026-09-28',
    amountPaid: 2200,
    pricePerLitre: 96.72,
    estimatedLitres: 22.75,
    odometer: 41998,
    distanceSinceLast: 318,
    mileage: 13.98,
    costPerKm: 6.92,
    fuelStation: 'Indian Oil, Sector 12',
    paymentMethod: 'Card',
    fuelType: 'Petrol',
  },
  {
    id: 'fuel-3',
    vehicleId: 'vehicle-1',
    date: '2026-09-14',
    amountPaid: 2000,
    pricePerLitre: 96.72,
    estimatedLitres: 20.68,
    odometer: 41680,
    distanceSinceLast: 290,
    mileage: 14.02,
    costPerKm: 6.9,
    fuelStation: 'BPCL, MG Road',
    paymentMethod: 'Cash',
    fuelType: 'Petrol',
  },
  {
    id: 'fuel-4',
    vehicleId: 'vehicle-1',
    date: '2026-09-01',
    amountPaid: 1800,
    pricePerLitre: 95.5,
    estimatedLitres: 18.85,
    odometer: 41390,
    distanceSinceLast: 268,
    mileage: 14.22,
    costPerKm: 6.72,
    fuelStation: 'HP Petrol Pump, Sector 18',
    paymentMethod: 'UPI',
    fuelType: 'Petrol',
  },
  {
    id: 'fuel-5',
    vehicleId: 'vehicle-1',
    date: '2026-08-18',
    amountPaid: 2300,
    pricePerLitre: 95.5,
    estimatedLitres: 24.08,
    odometer: 41122,
    distanceSinceLast: 330,
    mileage: 13.7,
    costPerKm: 6.97,
    fuelStation: 'Indian Oil, Sector 12',
    paymentMethod: 'UPI',
    fuelType: 'Petrol',
  },
  {
    id: 'fuel-6',
    vehicleId: 'vehicle-1',
    date: '2026-08-05',
    amountPaid: 2100,
    pricePerLitre: 95.5,
    estimatedLitres: 21.99,
    odometer: 40792,
    distanceSinceLast: 298,
    mileage: 13.55,
    costPerKm: 7.05,
    fuelStation: 'BPCL, MG Road',
    paymentMethod: 'Card',
    fuelType: 'Petrol',
  },
  {
    id: 'fuel-7',
    vehicleId: 'vehicle-2',
    date: '2026-10-02',
    amountPaid: 500,
    pricePerLitre: 96.72,
    estimatedLitres: 5.17,
    odometer: 18200,
    distanceSinceLast: 198,
    mileage: 38.3,
    costPerKm: 2.53,
    fuelStation: 'HP Petrol Pump, Sector 18',
    paymentMethod: 'Cash',
    fuelType: 'Petrol',
  },
];

export const MOCK_MAINTENANCE = [
  {
    id: 'maint-1',
    vehicleId: 'vehicle-1',
    serviceType: 'Engine Oil Change',
    date: '2026-08-10',
    odometer: 40500,
    cost: 1800,
    notes: 'Changed to Mobil 1 5W-30 synthetic oil. Next service at 43500 km.',
    nextServiceKm: 43500,
    nextServiceDate: null,
  },
  {
    id: 'maint-2',
    vehicleId: 'vehicle-1',
    serviceType: 'Tyre Rotation & Balancing',
    date: '2026-07-20',
    odometer: 39200,
    cost: 600,
    notes: 'All tyres rotated and balanced.',
    nextServiceKm: null,
    nextServiceDate: null,
  },
  {
    id: 'maint-3',
    vehicleId: 'vehicle-2',
    serviceType: 'General Service',
    date: '2026-09-05',
    odometer: 17800,
    cost: 1200,
    notes: 'Oil, air filter, spark plug changed.',
    nextServiceKm: 20800,
    nextServiceDate: null,
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif-1',
    type: 'insight',
    title: 'Fuel Insight',
    message: 'Your mileage is 6.2% lower than your recent average.',
    time: '2026-10-04T10:30:00',
    read: false,
  },
  {
    id: 'notif-2',
    type: 'maintenance',
    title: 'Maintenance Reminder',
    message: 'Your next service may be due in ~1,150 km.',
    time: '2026-10-01T09:00:00',
    read: false,
  },
  {
    id: 'notif-3',
    type: 'summary',
    title: 'Monthly Summary',
    message: 'You spent ₹4,700 on fuel in September 2026.',
    time: '2026-10-01T08:00:00',
    read: true,
  },
];

export const FUEL_TYPES = ['Petrol', 'Diesel', 'CNG', 'Electric'];
export const VEHICLE_TYPES = ['Car', 'Bike', 'Truck', 'Van'];
export const PAYMENT_METHODS = ['Cash', 'UPI', 'Card'];
